### ISSUE TITLE
Testing infrastructure

### ISSUE THREAD

**Issue by fsmanuel** [67P/kredits-contracts#103]
We need to setup a testing infrastructure for solidity and the wrapper.

TODO:
- [x] Code linting https://github.com/67P/kredits-contracts/pull/97
- [ ] Wrapper contracts
- [ ] Serializer https://github.com/67P/kredits-web/pull/103
- [ ] Solidity contracts

**Comment by bumi** [comment]
maybe @haythem96 has some input or can help with the solidity tests?

**Comment by haythem96** [comment]
sure, will work on this those days...

**Comment by skddc** [comment]
I think linting is there now, right?

**Comment by haythem96** [comment]
> I think linting is there now, right?

Yes
