### ISSUE TITLE
Allow arbitrary accounts in profiles

### ISSUE THREAD

**Issue by raucao** [67P/kredits-contracts#115]
Currently serializes/deserializes with special account properties on the root level of the contibutor attributes.

**Comment by bumi** [comment]
I think we now do that but there is a bug that results in duplicated account entries on update. 
The accounts array is set and the (e.g.) `github_*` accessors also add an account entry.

**Comment by skddc** [comment]
I remember you adding this feature, so both the commit and PR didn't ref this issue.
