### ISSUE TITLE
Add amount to vote

### ISSUE THREAD

**Issue by fsmanuel** [67P/kredits-contracts#12]
It would be great if the voter can provide the amount she or he would like to distribute to the proposal recipient.
To make it easier for the voter we should be able to attach a base amount to the proposal (could be in IPFS) or even let the proposal recipient set a minimum amount she or he wants to receive.

**Comment by skddc** [comment]
I don't see how this makes sense. A vote is on a proposal for an amount. It is meaningless if it can be an arbitrary value, as no other vote can match it.

Also, there is nothing being distributed by the voter. The kredits are newly minted by the contract when a contribution is confirmed by a quorum of votes.

Maybe you can explain the details of why and how this would work a bit more?

**Comment by skddc** [comment]
Closing, as there's no new information. Feel free to re-open, of course.
