### ISSUE TITLE
Deploying contracts from root directory fails

### ISSUE THREAD

**Issue by skddc** [67P/kredits-contracts#137]
E.g. with `npm bootstrap`:

![Screenshot from 2019-06-13 15-04-44](https://user-images.githubusercontent.com/842/59434869-a9147800-8dec-11e9-8928-7ed35a087070.png)

(The same command still works when run from the contract's own package directory.)

**Comment by skddc** [comment]
@bumi linked some changes on chat, which could be relevant: https://github.com/aragon/aragon-cli/commit/5aa4a654fc9ac1355574d6609dd241d30b4fa9df

And when running the `deploy:apps` script outside of npm scripts, then it still works. So for now you can just do this on the command line in the root dir:

    ./scripts/every-app.sh 'aragon apm publish major'

**Comment by bumi** [comment]
fyi. I've also got that error when running `aragon apm publish major` inside one of the apps (`apps/contribution`) 

```
apps/contribution@feature/ipfs-pinner  » aragon apm publish major --debug=true
Check IPFS [started]
Start IPFS [started]
→ IPFS is started, checking CORS config
Start IPFS [completed]
Add local files [started]
Add local files [completed]
Check IPFS [completed]
Applying version bump (major) [started]
Applying version bump (major) [completed]
Deploy contract [started]
Compile contracts [started]
Compile contracts [completed]
Deploy 'Contribution' to network [started]
→ Deploying 'Contribution' to network
Deploy 'Contribution' to network [completed]
Generate deployment artifacts [started]
Generate deployment artifacts [completed]
Deploy contract [completed]
Determine contract address for version [started]
Determine contract address for version [completed]
Building frontend [started]
Building frontend [skipped]
→ Build script not defined in package.json
Prepare files for publishing [started]
Prepare files for publishing [completed]
Generate application artifact [started]
Generate application artifact [completed]
Publish kredits-contribution.open.aragonpm.eth [started]
Generating transaction [started]
→ Fetching DAO at 0x9a348D0c3f55c2B3f6A400CC1BE71c882Ff1bdC3...
Generating transaction [failed]
→ Could not create transaction due to missing app artifact
Publish kredits-contribution.open.aragonpm.eth [failed]
→ Could not create transaction due to missing app artifact
```

**Comment by bumi** [comment]
related: #140 - that might hopefully fix it.

**Comment by skddc** [comment]
It would be very useful if you added this information the other way around, so the PR is linked including its status in here. And if you use the right keyword, then it will also close the ref'ed issue when merged.

**Comment by bumi** [comment]
can we close this? does it work for you now @skddc

**Comment by skddc** [comment]
Does it work for you? Haven't tested it yet.

**Comment by bumi** [comment]
it does.
