### ISSUE TITLE
Get rid of warnings on Kredits initialization

### ISSUE THREAD

**Issue by raucao** [67P/kredits-contracts#150]
Every kredits client displays 5 rows of warnings when it initalizes a new Kredits prototype:

```
WARNING: Multiple definitions for newAppProxy
WARNING: Multiple definitions for newAppProxyPinned
WARNING: Multiple definitions for newAppInstance
WARNING: Multiple definitions for newPinnedAppInstance
WARNING: Multiple definitions for canPerform
```

**Comment by bumi** [comment]
I looked at that awhile ago but did not find a solution. I think it is related to ethers.js

**Comment by skddc** [comment]
Example from ipfs-pinner:

![Screenshot from 2019-07-02 18-45-56](https://user-images.githubusercontent.com/842/60531200-b1c8e180-9cfa-11e9-85f3-f48698505707.png)

**Comment by skddc** [comment]
Found the code in ethers (you can search for "Multiple definitions" in there). We'd have to do a PR to maybe change the log level it's using for those warnings (to `debug` instead of `warn`).
