### ISSUE TITLE
Exceptions on Travis (without tests failing)

### ISSUE THREAD

**Issue by raucao** [67P/kredits-contracts#163]
Seeing a lot of test runs actually failing, but with the failures being ignored:

     Error: Cannot find module '@aragon/test-helpers/assertThrow'

Example: https://travis-ci.org/67P/kredits-contracts/builds/569916451

**Comment by skddc** [comment]
Just ran into this again with #194.

@haythem96 Want to take a look at this perhaps? Would sure be nice to have a working test suite...
