### ISSUE TITLE
Contributor update/serialization failing

### ISSUE THREAD

**Issue by raucao** [67P/kredits-contracts#168]
No idea where it's turning the UID into a string, but at the point where `kredits-web` is calling the update function it's still a number:

![Screenshot from 2019-08-14 15-25-55](https://user-images.githubusercontent.com/842/63024711-0fc71800-bea8-11e9-88c2-9c8b6ea14dd8.png)

I think this is a regression, because it worked before, and we changed some things about serialization not long ago.

**Comment by skddc** [comment]
LOL, I just tried it locally, and instead of updating the existing accounts, it added *two* new sets for the updated accounts at once:
![Screenshot from 2019-08-14 18-48-26](https://user-images.githubusercontent.com/842/63039827-722e1180-bec4-11e9-876e-089a0d29c7ff.png)

**Comment by skddc** [comment]
Interestingly, there's no string vs. integer validation issue locally, but a different number error *after* updating the contributor. It looks like the update event is returning a larger number type than a normal contributor GET.

**Comment by skddc** [comment]
Note from call: we'll try to revert the change that broke it, and re-submit it in the future, after more testing.

**Comment by skddc** [comment]
@bumi What about reverting that commit? It's been almost a week again...
