### ISSUE TITLE
Create a vault app that can hold ETH for the DAO

### ISSUE THREAD

**Issue by bumi** [67P/kredits-contracts#169]
The DAO needs to be able to receive ETH ~~and other tokens (let's start with ETH only)~~ which will be used to distribute to token owners and to pay for expenses. 

For this we need a "vault" app that will handle the funds.

**Comment by bumi** [comment]
@haythem96 already started with #145

**Comment by haythem96** [comment]
moved the PR here #172

**Comment by skddc** [comment]
Note from call: we agreed to use Aragon's vault app instead of our custom one. See #173.
