### ISSUE TITLE
Migrate to the new ipfs-http-client API

### ISSUE THREAD

**Issue by raucao** [67P/kredits-contracts#181]
* [42.0.0 release notes](https://github.com/ipfs/js-ipfs-http-client/releases/tag/v42.0.0)
* [Migration guide](https://gist.github.com/alanshaw/04b2ddc35a6fff25c040c011ac6acf26)

**Comment by skddc** [comment]
Official release announcement is out: https://blog.ipfs.io/2020-02-13-js-ipfs-0-41/

**Comment by fsmanuel** [comment]
Wait for the first patch release!
