### ISSUE TITLE
Batch proposal voting

### ISSUE THREAD

**Issue by bumi** [67P/kredits-contracts#19]
Right now it is only possible to vote for one proposal. 
To make it quicker it should be possible to vote in batches with one transaction. 

PR: https://github.com/67P/truffle-kredits/pull/20

**Comment by bumi** [comment]
potential problems: 
* need to see how to pass an array as parameter
* gas estimation might not work because of an array of an unknown length

**Comment by skddc** [comment]
> Both variably and fixed size arrays are supported in storage and as parameters of external functions: ...

https://ethereumbuilders.gitbooks.io/guide/content/en/solidity_tutorials.html

**Comment by bumi** [comment]
https://github.com/67P/truffle-kredits/pull/20#issuecomment-379686538

**Comment by skddc** [comment]
Actually, this is kind of obsolete, now that votes are not the normal means of confirming contributions anymore.
