### ISSUE TITLE
Replicate/mirror/port data from one network to another

### ISSUE THREAD

**Issue by bumi** [67P/kredits-contracts#197]
In order to have useful test data we should replicate data from our main instance to some test instance (potentially on a different network) 

### Current ideas/plan

*added June 1, 2021*

* [ ] Script to retrieve all existing data (except ERC20 ownership) from current network; write to local file and/or IPFS document
* [ ] Script to create all contribution and contributor objects from backup anew (careful with IDs)
* [ ] Contract addition: allow setting `confirmedAtBlock` dynamically when creating object, until migration done. Set boolean flag to disallow afterwards

**Comment by skddc** [comment]
I was just wondering if there's a fairly easy way for me to mirror the current Rinkeby data to my local instance. Then I had an idea: could this be a function that is only called when deploying the contracts/DAO? By this, I mean it wouldn't usually be allowed to e.g. create a contribution with a `confirmed_at` in the past, but I guess during contract deployment the function could actually do this, right?
