### ISSUE TITLE
Validate Contributor/Contribution details using json schema

### ISSUE THREAD

**Issue by bumi** [67P/kredits-contracts#30]
The Contributor/Operator class currently does not validate the data against the json schema from kosmos-schemas. To prevent storing invalid data we should validate those before uploading to ipfs and to the smart contract.

**Comment by skddc** [comment]
¡Muy importante!

**Comment by skddc** [comment]
Btw, it's only one function call, documented nicely in the schemas doc: https://github.com/67P/kosmos-schemas#usage

**Comment by skddc** [comment]
Bumping this one. We already have some invalid documents in IPFS docs linked from the Kovan data.

**Comment by skddc** [comment]
All done.
