### ISSUE TITLE
Load contract address from ENS

### ISSUE THREAD

**Issue by bumi** [67P/kredits-contracts#31]
The [Ethereum Name Service](https://ens.domains/) could be an option to assign a name to the kredits organization registry address. This way the contracts wrapper could load the address from ENS.

**Comment by fsmanuel** [comment]
Is this still relevant?

**Comment by bumi** [comment]
yes, I think we could still get a ENS name to point to the Kredits DAO address.

**Comment by skddc** [comment]
Or [RNS](https://docs.rns.rsk.co/) later on. ;)
