### ISSUE TITLE
ATTENTION: repos renamed!

### ISSUE THREAD

**Issue by skddc** [67P/kredits-contracts#45]
Just so it comes to everyone's attention: I have renamed the contracts GitHub repos just now. This repo now contains what was `truffle-kredits` before, and the old repo of `kredits-contracts` is now available as [kredits-contracts-legacy](https://github.com/67P/kredits-contracts-legacy).

@bumi @fsmanuel Plz confirm when you have changed your Git remotes, then we can close the issue.

**Comment by fsmanuel** [comment]
@skddc Updated!
