### ISSUE TITLE
System components

### ISSUE THREAD

**Issue by fsmanuel** [67P/kredits-contracts#5]
As far as I understand the situation we have the following components in our system:

- [IPFS](https://ipfs.io/)
- uPort
  - identity
- [truffle-kredits](https://github.com/67P/truffle-kredits)
  - ETH blockchain access
  - ETH smart contracts deployment
  - smart contracts
  - proxy contracts
  - migratable contracts via proxy
  - testing
- [kosmos-schemas](https://github.com/67P/kosmos-schemas)
  - JSON schemas for IPFS data
- [hubot-kredits](https://github.com/67P/hubot-kredits)
- [kredits-web](https://github.com/67P/kredits-web)
  - frontend/gui

Please add everything I forgot!

**Comment by bumi** [comment]
This is documented in the wiki: https://wiki.kosmos.org/Kredits#Software - which we should extend/update. 

* [IPFS](https://ipfs.io/) is the system to store larger files. 
* uPort is not used right now - it could be an contributor identity provider. 

missig is [hubot-kredits](https://github.com/67P/hubot-kredits) which is handling github webhooks to create proposals and has IRC integration.

**Comment by fsmanuel** [comment]
Thanks! I updated the list and will read the wiki.

**Comment by fsmanuel** [comment]
Yeah! I think we can update the wiki as a first task next week. I'll just use the issues to get a better understanding and ask all the questions.

**Comment by fsmanuel** [comment]
Is the parity server on https://parity.kosmos.org:8545 also part of the system?

**Comment by skddc** [comment]
Well, it's running our current beta chain that we use with the deployed system that's in place. If a PR is merged or an issue closed with a kredits label attached, hal8000 will create proposals on that chain for example.

**Comment by skddc** [comment]
> Yeah! I think we can update the wiki as a first task next week. I'll just use the issues to get a better understanding and ask all the questions.

I just updated the wiki page to be more or less up to date. But there's still some information missing. Earn you some Kovan kredits and help me add more content! :)

Closing this issue in favor of the wiki page.
