### ISSUE TITLE
Lazy consensus

### ISSUE THREAD

**Issue by skddc** [67P/kredits-contracts#50]
Trying to document what we discussed in person a couple times:

**Problem:** Having to vote on every single contribution confirmation proposal is both tedious, manual labor as well as expensive, because every vote has to be paid for.

**Solution:** Never vote on this type of proposal by default, but only start a voting process in case someone triggers it via a veto/rejection.

Ideas:

* Have a reasonable timeout for auto-confirmation/vetos, like e.g. one week or 10 days (set as block height)
* <del>We could issue kredits immediately, but make them non-transferable until the contribution is finally confirmed/not rejected. I'm not sure the added complexity is worth it, esp. considering that we're adding another ERC721 token for contributions, in addition to the fungible kredits token.</del> Not necessary. Kredits tokens (ERC20) can be withdrawn at once for all contributions which still have them available to withdraw and which have passed the veto period.
* Only allow auto-confirming proposals by core team members (and later dynamically based on past contributions), in order to prevent spamming and scamming.

---
Feel free to edit this entry, in case I forgot something.

**Comment by bumi** [comment]
Missing in PR #62: 
* what timeout shall we set before kredits can be withdrawn? 
* a veto does not automatically create a proposal. BUT I think this should be done from the client and not in the contract. Doing it in the contract would make vetos expensive and I also we can not be sure that a veto means a proposal should automatically be created. 
* we need to set the number of votes (or logic) that are required to execute a proposal. btw. a proposal will create a Contribution which currently also can be vetoed.

**Comment by skddc** [comment]
> what timeout shall we set before kredits can be withdrawn?

We said one week to start with. Should experiment with that in actual usage. I still think that's a good timeframe, although 2 weeks might be even better. If it's too long, then people don't have an incentive to regularly check the project dashboard.

> a veto does not automatically create a proposal. BUT I think this should be done from the client and not in the contract. Doing it in the contract would make vetos expensive and I also we can not be sure that a veto means a proposal should automatically be created.

Good thinking. Fully agree.

> we need to set the number of votes (or logic) that are required to execute a proposal. btw. a proposal will create a Contribution which currently also can be vetoed.

I think we should not have contribution proposals in the launch version in the first place. This is an add-on feature that is not required for our MVP feature set. So if we really keep it in there, it still doesn't have to be complete or usable for MVP (as long as it's not a security risk).

**Comment by skddc** [comment]
![rejoicing](https://user-images.githubusercontent.com/842/56661467-b25d5000-6699-11e9-8df8-96a3315fd04a.gif)
