### ISSUE TITLE
Let (unregistered) contributors claim Contributions/Tokens

### ISSUE THREAD

**Issue by bumi** [67P/kredits-contracts#54]
Right now every contributor requires an Ethereum wallet and needs to be added as a contributor before tokens can be issued.  This is a bit of an overhead and all contributors need to be convinced using kredits before proposals can be made.

To make this easier we should think of a concept to claim contributions AFTER the voting. So proposals can be created and executed for any contribution even if the contributor is not yet in the system.

**Comment by skddc** [comment]
I was thinking about this just now, and here's a thought: how about we handle this entirely off-chain for now, and simply queue those contributions in hubot-kredits, with the site and account that it gets the hook from?

We could then listen to contributor creation and update events from the contract and match those to the queued contributions. Meaning when someone's details are added, no matter if for the first time or updating with a new site account later on, the bot can go and create those contributions using the date and time it recorded them at.

**Comment by skddc** [comment]
I was thinking about this just now, and here's a thought: how about we handle this entirely off-chain for now, and simply queue those contributions in hubot-kredits, with the site and account that it gets the hook from?

We could then listen to contributor creation and update events from the contract and match those to the queued contributions. Meaning when someone's details are added, no matter if for the first time or updating with a new site account later on, the bot can go and create those contributions using the date and time it recorded them at.

**Comment by bumi** [comment]
YES, let's do this off-chain for now. 
and we should do any of such blockers off-chain for now until we have enough time to get it working on-chain.
