### ISSUE TITLE
update ethers.js to 4.0

### ISSUE THREAD

**Issue by bumi** [67P/kredits-contracts#57]
Ethers.js released a new version. The new version has some breaking changes but updating should be easy. 
have a look a the [migration guide](https://docs.ethers.io/ethers.js/html/migration.html)

ethers.js is also a dependency in kredits-web and must be updated at the same time.

**Comment by bumi** [comment]
done in #62

**Comment by skddc** [comment]
FYI: if you reference the issues from the PR, then the PR will be linked, including its status. And if you use the right keyword, like e.g. "closes #number", then the issue will also be closed automatically when the PR is merged.
