### ISSUE TITLE
Review the usage of AragonOS

### ISSUE THREAD

**Issue by bumi** [67P/kredits-contracts#59]
It seems Aragon has made some great progress and I from what I see and from my early experiments I really like the project. 
We should review if we can use [AragonOS](https://hack.aragon.org/docs/aragonos-intro.html) and maybe even make our contracts compatible with aragon. 

Upgreadability, Permission control and Forwards solve topics that we had often discussed before and are hard to implement.

**Comment by skddc** [comment]
Good point. Maybe you could document what you researched so far in the wiki, to share your current knowledge and results.

**Comment by skddc** [comment]
@bumi Shouldn't the kredits for this one be distributed via wiki edits?

**Comment by bumi** [comment]
maybe I am a bit biased because I really like a lot from what I have read and seen online. And I like their approach. ;)

But it seems that the AragonOS stuff could be useful. The functionality it provides addresses topics that we have been talking a lot about and have been struggling with: Upgreadability, Permission control, Forwarders. 

Documentation: [hack.aragon.org](https://hack.aragon.org/docs/aragonos-intro.html)

The [aragon-cli](https://hack.aragon.org/docs/cli-usage.html) also provides some inspiration to our CLI/scripts. It is a wrapper around some tools and to interact with the smart contracts. e.g. to run dev-chains (similar to our npm run ganache)

**Comment by bumi** [comment]
yeah, you are right. should be distributed through the wiki and added to the wiki.

**Comment by skddc** [comment]
Fwiw, I'm also slightly biased, but against it. Because whenever I looked at it, it seemed to me like it was geared too much towards digital corporations instead of cooperatives. That's why I think we need to put in the effort to properly review it and document the findings in detail, including a resulting list of benefits and drawbacks.

**Comment by bumi** [comment]
please note that I am talking about AragonOS here. not the aragon app/network

**Comment by bumi** [comment]
Started collecting notes and links here: https://wiki.kosmos.org/Aragon

**Comment by bumi** [comment]
aragon will be used in #62
