### ISSUE TITLE
System data

### ISSUE THREAD

**Issue by fsmanuel** [67P/kredits-contracts#6]
What I can not really evaluate is what kind of data the system should handle.
I got that we need to save

- Identity information for a address
- Proposals
- Address balance

What else needs to be on the blockchain and what other data do we have?

**Comment by bumi** [comment]
Generally as little data as possible should be stored in the smart contract. Anything that goes there costs gas. - So bigger files should be made available through IPFS. 
For example: the for the user profile we store an IPFS hash and all the user details in IPFS.

But yeah, generally we right now have:
* [Contributors](https://github.com/67P/kredits-contracts/blob/operator/contracts/Contributors.sol)
* [Proposals](https://github.com/67P/kredits-contracts/blob/operator/contracts/Operator.sol)
* [Tokens](https://github.com/67P/kredits-contracts/blob/operator/contracts/Token.sol)

**Comment by skddc** [comment]
The JSON Schema definitions for the IPFS documents we store can be found here: https://github.com/67P/kosmos-schemas
