### ISSUE TITLE
Review usage of RSK

### ISSUE THREAD

**Issue by raucao** [67P/kredits-contracts#60]
[RSK](https://www.rsk.co/) is a Bitcoin sidechain, that uses a federated set of nodes to run smart contracts. Value store/transfer happens via pegged BTC, secured by the main chain.

It does sound enticing to me in general, but I don't know how feasible it is to run our contracts on RSK without changing much. They do claim basically full compatibility though:

> RSK smart contracts are programmed on Solidity and RSK VM is highly compatible with Ethereum VM. Future versions of the RSK Platform will include improvements to Ethereum VM which might require minor changes to the smart contracts in order to use this new functionalities.

**Comment by skddc** [comment]
Turns out they published penty of documentation around the end of January this year, and pretty much everything seems to be 100% compatible with Ethereum in terms of app development and such:

https://github.com/rsksmart/rskj/wiki

**Comment by skddc** [comment]
Useful links:

* [JSON RPC API compatibility matrix](https://github.com/rsksmart/rskj/wiki/JSON-RPC-API-compatibility-matrix)
* https://stats.rsk.co
* https://explorer.rsk.co

**Comment by skddc** [comment]
Update: we have a testnet RSK node running on Andromeda now, currently syncing the blockchain. Installation via the PPA worked like a charm, including systemd service and all. Haven't changed much of the default config so far. You can find it in `/home/rsk/rsk-testnet.conf` (symlinked from `/etc/rsk/node.conf`).

**Comment by skddc** [comment]
Using with Metamask and getting some test RBTC:

1. Add a custom RPC server (network switcher), set e.g. to an [official public testnet node](https://github.com/rsksmart/rskj/wiki/RSK-public-nodes): `https://public-node.testnet.rsk.co/`
2. Copy account address and get you some RBTC from https://faucet.testnet.rsk.co

**Comment by skddc** [comment]
Preliminary research is concluded. I don't see any hindrance to deploying exactly what we have right now to RSK testnet and see if it works.

I also don't see why we wouldn't be able to deploy to mainnet if we see that our code works on testnet. We can run our own node that can deploy the contracts.

@bumi Ping me, so we can coordinate and hopefully pair on this! Thanks.
