### ISSUE TITLE
Unify hashDigest

### ISSUE THREAD

**Issue by fsmanuel** [67P/kredits-contracts#75]
Can we address this issue as well:

https://github.com/67P/kredits-contracts/blob/93e0b30b357e69a892b0c3187a813b95f0a1d619/lib/contracts/contributor.js#L24-L25

I have ~17~ 9 `ipfsHash` matches in https://github.com/67P/kredits-contracts/blob/master/apps/contributor/contracts/Contributor.sol

Update:
I think we don't use this function at all:
https://github.com/67P/kredits-contracts/blob/93e0b30b357e69a892b0c3187a813b95f0a1d619/apps/contributor/contracts/Contributor.sol#L72-L80

**Comment by skddc** [comment]
PRs welcome!

**Comment by bumi** [comment]
actually I have this code that I just commited: https://github.com/67P/kredits-contracts/pull/79
but this needs testing...
