### ISSUE TITLE
Add pagination to the wrapper

### ISSUE THREAD

**Issue by fsmanuel** [67P/kredits-contracts#81]
I'll add an offset pagination to the wrapper. Any suggestions for the default limit?

**Comment by bumi** [comment]
:+1: 
maybe :game_die: 25 

btw. I think we should default to returning the newest first. (in all the `all()`/collection function. what do you think? (unrelated of this issue, though)

**Comment by fsmanuel** [comment]
I'll generalize the `all()` to make the pagination work. So I'll consider sorting as well!

**Comment by fsmanuel** [comment]
closed via #96
